### ISSUE TITLE
change the route

### ISSUE THREAD

**Issue by udaykumar-8329** [Raghuveer1997/Sentiment-Analysis#1]
![Screenshot_2021-07-09-21-11-20-12](https://user-images.githubusercontent.com/35301592/125103729-48a2b280-e0fa-11eb-818e-9496bbd0d6b3.jpg)

change the route to predict

**Comment by Raghuveer1997** [comment]
measure_sentiments route to predict right

**Comment by udaykumar-8329** [comment]
yes
